/**
 * This class defines the Login object handled by the PasswordManager application.
 *
 * @author TeamFive Technology
 * @version 1.0.0
 */
package com.teamfivetech.passwordmanager.core;

public class Login {
    // FIELDS
    static int counter = 1;

    private int id;
    private String siteName;
    private String userName;
    private String password;

    // METHODS
    // constructors

    /**
     * Public constructor to create a new Login object.
     *
     * @param siteName String representing the site name entered by the user.
     * @param userName String representing the username entered by the user.
     * @param password String representing the password either entered by the user, or generated by the application.
     */
    public Login(String siteName, String userName, String password) {
        setId(counter++);
        setSiteName(siteName);
        setUserName(userName);
        setPassword(password);
    }

    // accessors
    private static int getCounter() {
        return counter;
    }

    /**
     * Method used to set the counter that is iterated to automatically generate the Login ID. Counter is reset to 1 every time the LoginIO read() is called.
     * @param counter an integer value used to define the starting point for Login ID numbers
     */
    public static void setCounter(int counter) {
        Login.counter = counter;
    }

    public int getId() {
        return id;
    }

    private void setId(int id) {
        this.id = id;
    }

    /**
     * Method used to return a Login object's siteName field.
     * @return a String value of the siteName.
     */
    public String getSiteName() {
        return siteName;
    }

    private void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    /**
     * Method used to return a Login object's userName field.
     * @return a String value of the userName
     */
    public String getUserName() {
        return userName;
    }

    private void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Method used to return a Login Object's password field.
     * @return a String value of the password.
     */
    public String getPassword() {
        return password;
    }

    private void setPassword(String password) {
        this.password = password;
    }

    /**
     * toString() override method used in writing the Login object to a .csv file.
     * @return a custom string listing the Login object's fields separated by commas.
     */
    @Override       // class Object
    public String toString() {
        return getId() + "," + getSiteName() + "," + getUserName() + "," + getPassword();
    }
}