package com.teamfivetech.passwordmanager.core;

import java.util.*;
import java.util.concurrent.Callable;
import java.util.stream.Collectors;

/**
 * Class that is used to generate randomized passwords from 2 options.
 * Option 1: Generate from preset security profile. Method name: generate(SecurityLevel securityLevel)
 * Option 2: Generate from length and complexity. Method name: generate(int length, Map<String,Boolean> generateOptions)
 * @author TeamFive Technology
 * @version 1.0.0
 */
public class PasswordGenerator {
    // ASCII code [A-Z]
    private static final int UPPERCASE_MIN = 65;
    private static final int UPPERCASE_MAX = 90;
    // ASCII code [a-z]
    private static final int LOWERCASE_MIN = 97;
    private static final int LOWERCASE_MAX = 122;
    // ASCII code [0-9]
    private static final int NUMBER_MIN = 48;
    private static final int NUMBER_MAX = 57;
    // Allowed symbols in password
    private static final String SYMBOLS = "!@#$%^&*().";
    private static final Random rand = new Random();
    // HashMap keys for invoking corresponding methods
    public static final String GET_RANDOM_LOWER = "getRandomLower";
    public static final String GET_RANDOM_UPPER = "getRandomUpper";
    public static final String GET_RANDOM_NUMBER = "getRandomNumber";
    public static final String GET_RANDOM_SYMBOL = "getRandomSymbol";

    // Store generate methods in HashMap for easy filtering and invoking within an iteration
    private final Map<String, Callable<String>> generateActions = new HashMap<>() {{
        put(GET_RANDOM_LOWER, () -> getRandomLower());
        put(GET_RANDOM_UPPER, () -> getRandomUpper());
        put(GET_RANDOM_NUMBER, () -> getRandomNumber());
        put(GET_RANDOM_SYMBOL, () -> getRandomSymbol());
    }};

    /**
     * Generates a password based on preset security profiles
     * @param securityLevel (LOW(8), MEDIUM(12), HIGH(16))
     * @return random, autogenerated String. (may include uppercase, lowercase, number, and/or symbol)
     */
    public String generate(SecurityLevel securityLevel) {
        String result = "";
        // Store desired actions (generateActions HashMap keys)
        List<String> actions = new ArrayList<>();
        switch (securityLevel) {
            // 8 length, 4 upper, 4 lower
            case LOW:
                actions.add(GET_RANDOM_UPPER);
                actions.add(GET_RANDOM_LOWER);
                result = generateByLengthActions(securityLevel.getPasswordLength(), actions);
                break;
            // 12 length, 4 upper, 4 lower, 4 number
            case MEDIUM:
                actions.add(GET_RANDOM_UPPER);
                actions.add(GET_RANDOM_LOWER);
                actions.add(GET_RANDOM_NUMBER);
                result = generateByLengthActions(securityLevel.getPasswordLength(), actions);
                break;
            // 16 length, 4 upper, 4 lower, 4 number, 4 symbol
            case HIGH:
                actions.add(GET_RANDOM_UPPER);
                actions.add(GET_RANDOM_LOWER);
                actions.add(GET_RANDOM_NUMBER);
                actions.add(GET_RANDOM_SYMBOL);
                result = generateByLengthActions(securityLevel.getPasswordLength(), actions);
                break;
            default:
                System.out.println("Invalid security level");
        }
        return result;
    }

    /**
     * Generates a password from desired length, uppercase, lowercase, number, symbol
     * @param length (1,...)
     * @param generateOptions {getRandomLower, getRandomLower()},{getRandomUpper, getRandomUpper()}
     * @return random, autogenerated String. (may include uppercase, lowercase, number, and/or symbol)
     */
    public String generate(int length, Map<String,Boolean> generateOptions) {
        Map<String,Boolean> options = generateOptions.entrySet().stream()
                .filter(Map.Entry::getValue)
                .collect(Collectors.toMap(Map.Entry::getKey, stringBooleanEntry -> true));

        List<String> actions = new ArrayList<>(options.keySet());

        return generateByLengthActions(length, actions);
    }

    private Map<String, Callable<String>> findActionsByName(List<String> actions) {
        return generateActions.entrySet().stream()
                // keep only the map entries that match the actions list
                .filter(map -> actions.contains(map.getKey()))
                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
    }

    private String generateByLengthActions(int length, List<String> actions) {
        String result = "";
        List<String> characters = new ArrayList<>();
        int actionCount = findActionsByName(actions).values().size();

        if (actionCount == 0) return result;

        for (int i = 0; i < length; i += actionCount) {
            findActionsByName(actions).values().forEach(callable -> {
                try {
                    // Generate random character from helper method and add to list
                    characters.add(callable.call());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }

        // Trim any remaining characters that exceed desired length
        List<String> trimmedPassword = characters.subList(0, Math.min(characters.size(), length));
        // Randomize character index locations
        Collections.shuffle(trimmedPassword);
        // Join characters into single String and store in result
        result = String.join("", trimmedPassword);

        return result;
    }

    private String getRandomUpper() {
        int randomUpperAsciiCode = rand.nextInt(UPPERCASE_MAX - UPPERCASE_MIN + 1) + UPPERCASE_MIN;
        return Character.toString((char) randomUpperAsciiCode);
    }

    private String getRandomLower() {
        int randomUpperAsciiCode = rand.nextInt(LOWERCASE_MAX - LOWERCASE_MIN + 1) + LOWERCASE_MIN;
        return Character.toString((char) randomUpperAsciiCode);
    }

    private String getRandomNumber() {
        int randomUpperAsciiCode = rand.nextInt(NUMBER_MAX - NUMBER_MIN + 1) + NUMBER_MIN;
        return Character.toString((char) randomUpperAsciiCode);
    }

    private String getRandomSymbol() {
        int index = rand.nextInt(SYMBOLS.length());
        return Character.toString(SYMBOLS.charAt(index));
    }
}